<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-07-13T17:19:35 UYT" name="Suite" finished-at="2020-07-13T17:19:43 UYT" duration-ms="7321">
    <groups>
    </groups>
    <test started-at="2020-07-13T17:19:35 UYT" name="Validating User login" finished-at="2020-07-13T17:19:43 UYT" duration-ms="7321">
      <class name="Academy.HomePage">
        <test-method is-config="true" signature="initialize()[pri:0, instance:Academy.HomePage@7c2327fa]" started-at="2020-07-13T17:19:35 UYT" name="initialize" finished-at="2020-07-13T17:19:37 UYT" duration-ms="2073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method signature="basePageNavigation()[pri:0, instance:Academy.HomePage@7c2327fa]" started-at="2020-07-13T17:19:37 UYT" name="basePageNavigation" finished-at="2020-07-13T17:19:41 UYT" duration-ms="3364" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basePageNavigation -->
        <test-method signature="validateAppNavBar()[pri:0, instance:Academy.HomePage@7c2327fa]" started-at="2020-07-13T17:19:41 UYT" name="validateAppNavBar" finished-at="2020-07-13T17:19:41 UYT" duration-ms="255" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAppNavBar -->
        <test-method signature="validateAppTitle()[pri:0, instance:Academy.HomePage@7c2327fa]" started-at="2020-07-13T17:19:41 UYT" name="validateAppTitle" finished-at="2020-07-13T17:19:41 UYT" duration-ms="290" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateAppTitle -->
        <test-method signature="validateNavigationBarHome()[pri:0, instance:Academy.HomePage@7c2327fa]" started-at="2020-07-13T17:19:41 UYT" name="validateNavigationBarHome" finished-at="2020-07-13T17:19:42 UYT" duration-ms="426" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at Academy.HomePage.validateNavigationBarHome(HomePage.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateNavigationBarHome -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:Academy.HomePage@7c2327fa]" started-at="2020-07-13T17:19:42 UYT" name="teardown" finished-at="2020-07-13T17:19:43 UYT" duration-ms="256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- Academy.HomePage -->
    </test> <!-- Validating User login -->
  </suite> <!-- Suite -->
</testng-results>
